### PR TITLE
appveyor travis sh install change

### PR DESCRIPTION
**Pull request by jordansread**

### CODE REVIEW

**Comment by jordansread** [comment]
@lawinslow merge plz

**Comment by lawinslow** [comment]
What happened, did you kill your fork?

**Comment by jordansread** [comment]
no, just hopping on your open PR

**Comment by jordansread** [comment]
oh, that file. Yeah, no need to point to mine anymore. that was a ncdf4 artifact

**Comment by lawinslow** [comment]
I mean, is that file no longer available from your fork?

**Comment by lawinslow** [comment]
ah

**Comment by jordansread** [comment]
it is, but is outdated I think

**Pull request merged**
